version: '3.7'
services:
  ova-container:
    container_name: container-yolov5
    #platform: linux/arm64/v8
    platform: linux/amd64
    image: app-yolov5
    build: 
      context: .
      dockerfile: Dockerfile-jetsonxavier
    runtime: nvidia
    volumes:
      - /home/user/ova:/app/src/volumen
    environment:
      - VOL_PATH=/app/src/volumen