# Import python
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# Folder to save data in other machine
WORKDIR /app

# Folder from host to image container (/app)
COPY . .
RUN pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip3 install -r requirements.txt

# Change execution python folder
WORKDIR /app/src

CMD ["python3", "app.py"]