# Import python
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# Folder to save data in other machine
WORKDIR /app

# Folder from host to image container (/app)
COPY . .

RUN pip3 install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3
RUN pip3 install -r requirements.txt

# Change execution python folder
WORKDIR /app/src

CMD ["python3", "app.py"]